Fix devcontainer
rapidsai/rapids.ai pull request #393
Opened 2024-08-19 19:23 UTC by bdice

This PR fixes the devcontainer, which was erroring when failing to find `npm`. I believe this is because the Node feature had feature `"none"` instead of `"latest"`. I also made the `get_medium.py` script executable.

2024-08-20 17:16 UTC, raydouglass approved these changes

2024-08-20 17:47 UTC, ajschmidt8 commented
hold on. the "none" was intentional because `nvm` should read the Node version from https://github.com/rapidsai/rapids.ai/blob/main/.nvmrc during the init script:

- https://github.com/rapidsai/rapids.ai/blob/a518ed3ec25fcbcbea250ce697ddae290f7a7cf1/scripts/devcontainer-init.sh#L26-L27

Is that not what was happening?

2024-08-20 17:47 UTC, ajschmidt8 requested changes
Requesting changes to block until pending discussion is resolved

2024-08-20 18:04 UTC, bdice commented
I think the devcontainer init script failed to find npm. I will try to reproduce.

2024-08-20 20:50 UTC, bdice commented
Failure looks like this:
```bash
./scripts/devcontainer-init.sh: line 29: npm: command not found
```

2024-09-19 12:48 UTC, ajschmidt8 commented
> Failure looks like this:
> 
> ```shell
> ./scripts/devcontainer-init.sh: line 29: npm: command not found
> ```
> 
> There's no other helpful context. It gets through the `hugo config` command and then I assume it's failing because Node isn't installed.

Can we huddle to debug this? I'm unable to reproduce the issue on my end.

2024-10-16 17:50 UTC, bdice commented
Closing this optimistically, in hopes that the issue doesn't reoccur. If it does, I'll reach out to AJ to debug on a call.

2024-10-16 17:50 UTC, closed without merging