Add Polars GPU engine page
rapidsai/rapids.ai pull request #399
Opened 2024-09-10 23:00 UTC by exactlyallan

Staging cudf polars page for review and content updates.

2024-09-11 06:30 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +<!-- FAQ -->
Alan - Can we add FAQs in a sequential format with an accordian clickable format? This one seems a little tough to read right now. 

<!-- FAQ Section with Accordion -->
<section class="row section bg-rapids-gray padding-top-slant padding-bottom-slant">
  <div class="col">
    <div class="container">
      <h1 class="mb-4">Frequently Asked Questions</h1>
      
      <!-- Accordion Container -->
      <div class="accordion" id="faqAccordion">

        <!-- Accordion Item 1 -->
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Do I have to install any RAPIDS specific package for the GPU backend to work?
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              No, you just need to install Polars with a feature flag in your standard Python pip install command: 
              <br><code>pip install polars[gpu]--extra-index-url=https://pypi.nvidia.com</code>
            </div>
          </div>
        </div>

        <!-- Accordion Item 2 -->
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingTwo">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Can I use the cuDF backend for Polars on my local Windows machine?
            </button>
          </h2>
          <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              Yes, you can use the cuDF backend for Polars on a Windows machine by installing WSL2. Note: You would need WSL2 on a Windows 11 or above OS. For download and troubleshooting instructions, please visit <a href="#" target="_blank">RAPIDS installation</a> page.
            </div>
          </div>
        </div>

2024-09-11 06:33 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          <p>First, install the cuDF backend for Polars with a feature flag in your standard Python pip install command:</p>
This step in common in both default and custom configurations. Any chance we could keep the pip installation command just right after "How it works" section? Something like https://docs.google.com/document/d/1h2Ynp0sniNuQ1k7Cfx64DYauaLJnadIkVpWCrXudaK0/edit?

2024-09-17 03:04 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          data: [33, 65, 132],
[35,67,136]

2024-09-17 03:04 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          data: [12, 18, 32],
[12,19,32]

2024-09-17 03:05 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          data: [7, 11, 17, 41],
[7,12,17,41]

2024-09-17 03:05 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          data: [1, 2, 1, 4],
[1,2,1,3]

2024-09-17 03:08 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          <p class="subheading">RAPIDS cuDF is the go-to Polars backend for large datasets and compute heavy queries.</p>
Don't need this sentence --> RAPIDS cuDF is the go-to Polars backend for large datasets and compute heavy queries

2024-09-17 03:09 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +      <h1 class="mb-4"> The go-to Polars backend</h1>
Replace with 

PROCESS 100s OF MILLIONS OF ROWS IN SECONDS

2024-09-17 03:13 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          <h2><i class="fa-sharp fa-light fa-gear-complex-code"></i> Default GPU </h2>
Can we replace 'Default GPU' by 'Default GPU Backend'

2024-09-17 03:14 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +        <div class="col-md-6 py-6">
Can we replace `Custom GPU` by `Custom GPU Backend`

2024-09-17 20:26 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +      <h1 class="text-center mb-4"> Process 100s of Millions of Rows in Seconds </h1>
100s is appearing as 100S. If it defaults to all caps, can we use 'HUNDREDS'

PROCESS HUNDREDS OF MILLIONS OF ROWS IN SECONDS

2024-09-17 20:29 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          text: 'PDS-H benchmark 80GB query processing time across a range of dataset sizes'
Can we say - 

'Query Processing time across a range of dataset sizes' 

This is not just for 80 GB

2024-09-17 20:32 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +      labels: ['20GB', '40GB', '60GB'],
This is 80GB

2024-09-17 20:34 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          label: '.collect()',
Can we change this to 'Polars (CPU)'

2024-09-17 20:34 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          label: '.collect(engine="gpu")',
Can we change this to 'Polars (GPU)'

2024-09-17 20:35 UTC, exactlyallan commented on layouts/page/cudf-polars.html
> +      labels: ['20GB', '40GB', '60GB'],
does anything need to change?

2024-09-17 20:36 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          text: 'PDS-H benchmark 80GB top performing compute heavy queries with complex groupby and join operations'
Can we make this -

Top performing compute heavy queries with complex groupby and join operations (PDS-Benchmark; 80 GB dataset)

2024-09-17 20:38 UTC, singhmanas1 commented on layouts/page/cudf-polars.html
> +          <p class="fw-lighter text-center">*GPU: NVIDIA H100, CPU: Intel Xeon W9-3495X (Sapphire Rapids), Storage: Local NVMe derived from TPC-H but these results are not comparable to TPC-H results
Can we make this-

PDS-H benchmark | GPU: NVIDIA H100 | CPU: Intel Xeon W9-3495X (Sapphire Rapids) | Storage: Local NVMe <New line>
Note: PDS-H is derived from TPC-H but these results are not comparable to TPC-H results. [Learn More](https://github.com/pola-rs/polars-benchmark)

2024-09-17 23:23 UTC, bdice requested changes
First round of feedback.

2024-09-17 23:23 UTC, bdice commented on .devcontainer/devcontainer.json
Let’s not delete the devcontainer in this PR. I have used it before to help build the site.

2024-09-17 23:23 UTC, bdice commented on .gitignore
> +.devcontainer
This is not supposed to be ignored.

2024-09-17 23:23 UTC, bdice commented on assets/scss/rapidsai/__general.scss
> +  border-bottom-left-radius: 0.5rem;
Let’s define this in one line like `border-radius: 0 0 0.5rem 0.5rem;`

2024-09-17 23:23 UTC, bdice commented on layouts/page/learn-more.html
> +          <p>RAPIDS and Polars are collaborating to GPU accelerate Polars DataFrames, enabling workflows to utilize both the CPU and GPU to significantly speeding up workloads.
```suggestion
          <p>RAPIDS and Polars are collaborating to GPU accelerate Polars DataFrames, enabling workflows to utilize both the GPU and CPU to significantly speed up workloads.
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/learn-more.html
> +          <h2><i class="fa-light fa-gauge-circle-bolt"></i> Network-X Accelerator</h2>
```suggestion
          <h2><i class="fa-light fa-gauge-circle-bolt"></i> NetworkX Accelerator</h2>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +          <p>Pass <code>engine=”gpu”</code> to the Polars' collect API to add GPU acceleration to your data processing tasks like data aggregation, merge, window functions, and much more.</p>
```suggestion
          <p>Pass <code>engine="gpu"</code> to the Polars <code>collect</code> API to add GPU acceleration to your data processing tasks like data aggregation, merges, window functions, and much more.</p>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +            pip install polars[gpu] —extra-index-url=https://pypi.nvidia.com
Some kind of autocorrect butchered this. Be careful with dashes and quotes.
```suggestion
            pip install polars[gpu] --extra-index-url=https://pypi.nvidia.com
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                device=0, #This is the default
```suggestion
                device=0,  # This is the default
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                raise_on_fail=True, #Fail loudly if can't execute on the GPU
```suggestion
                raise_on_fail=True,  # Fail loudly if can't execute on the GPU
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +        <div class="col ">
```suggestion
        <div class="col">
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                    <code>pip install polars[gpu]--extra-index-url=https://pypi.nvidia.com</code>
```suggestion
                    <code>pip install polars[gpu] --extra-index-url=https://pypi.nvidia.com</code>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                  Can I use Polars GPU engine on my local Windows machine?
```suggestion
                  Can I use Polars GPU engine on a Windows machine?
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                  <p>Yes, you can use the Polars GPU engine on a Windows machine by installing WSL2. Note: You would need WSL2 on a Windows 11 or above OS. For download and troubleshooting instructio
```suggestion
                  <p>Yes, you can use the Polars GPU engine on a Windows machine by installing WSL2 (requires Windows 11 or higher). For download and troubleshooting instructions, please visit the <a href="https://docs.rapids.ai/install#wsl2" target="_blank">RAPIDS installation</a> page.</p>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                  <p>No, at the moment the GPU-based engine is only supported in Polars' python API.</p>
```suggestion
                  <p>No, at the moment the GPU-based engine is only supported in Polars' Python API.</p>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                  <p>The GPU engine currently supports most of the core expressions and data types, but not all. For a detailed list of supported expressions visit the <a href="https://docs.pola.rs/u
```suggestion
                  <p>The GPU engine currently supports most of the core expressions and data types, but not all. For a detailed list of supported expressions visit the <a href="https://docs.pola.rs/user-guide/gpu-support/" target="_blank">GPU Support page</a> on the Polars website.</p>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +                  <p>Raise an issue on <a href="https://github.com/pola-rs/polars/issues" target="_blank">Polars GitHub</a> and the project contributors will respond as soon as possible.</p>
```suggestion
                  <p>Raise an issue on the <a href="https://github.com/pola-rs/polars/issues" target="_blank">Polars GitHub</a> and the project contributors will respond as soon as possible.</p>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +          <p>Try Polars GPU engine on <a href="https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/accelerated_data_processing_examples/polars_gpu_engine_demo.ipynb" target
```suggestion
          <p>Try the Polars GPU engine on <a href="https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/accelerated_data_processing_examples/polars_gpu_engine_demo.ipynb" target="_blank">Google Colab <i class="fa-solid fa-arrow-up-right"></i> </a></p>
```

2024-09-17 23:23 UTC, bdice commented on layouts/page/polars-gpu-engine.html
> +          <p>Share feedback on the <a href="https://github.com/pola-rs/polars/issues" target="_blank">Polars GitHub Page <i class="fa-solid fa-arrow-up-right"></i> </a></p>
```suggestion
          <p>Share feedback on the <a href="https://github.com/pola-rs/polars/issues" target="_blank">Polars GitHub repository <i class="fa-solid fa-arrow-up-right"></i> </a></p>
```

2024-09-18 00:38 UTC, bdice approved these changes
I made a bunch of changes, and this is now good to go from my side.

2024-09-18 01:38 UTC, merged